### ISSUE TITLE
play intro once and loop music based on 1 file

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#109]
Instead of having two files for a music stage (intro,loop) we should use 1 file. Its possible to do so in phaser where you can just move the start marker on loop.

- [x] make it generic in core/sounds so we can do it with an music
- [x] should work will rollback and snapshots

**Comment by Skytrias** [comment]
The SoundLoop does this by assigning Phaser Sound Markers. 

Currently i create a new Sound object, set Markers for 
- Start ranging from 0 until the first loop point
- Main ranging from the first loop point to the second loop point,
- Test ranging from a few seconds before the second loop point to the second loop point to test looping quickly

The only issue i ran into was stopping the sounds. Normal looped Sounds stop immediatly but sounds that have are played through markers will run until they reached the end of the marker - only until that they stop. So as a fix i mute the sounds when .stop() is called.

But this also brings a problem since we need to unmute the sound when playing. This breaks our Mute Button tho since it resets the mute bool. So i had to implement a master mute variable to the modified Sound. That way everything works.
