### ISSUE TITLE
Finding support for class arrow functions

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#42]
Currently we have to prebind all our member functions in the constructor for each class.
This is tedious. We could change our classes to primitive objects, add transpilers, or its possible there is a new version of chrome that we can build via electron to have arrow function support.

I would like to avoid using transpilers because its slow development and complexity.
I don't want to turn classes into primitive objects because I likely suspect their will be draw backs.

**Comment by omenking** [comment]
https://stackoverflow.com/questions/45785117/arrow-functions-within-classes-are-not-supported-in-chrome-but-work-fine-through

**Comment by Skytrias** [comment]
search for "js creating bound objects":

good links: https://ponyfoo.com/articles/binding-methods-to-class-instance-objects

**Comment by nderscore** [comment]
I don't think you'll be able to get arrow function methods without Babel at this point :(

You could do something hacky with a super class that auto-binds all methods of a class that extends it...
https://gist.github.com/nderscore/00896f2d7f06e3a0bad47bc436a8c0b1


But, is it really necessary to pass around class methods by reference? It would be a lot easier to just pass a reference to the instance so that context isn't lost. And in the few scenarios where you really need to, just wrap the method in an arrow function...

For example: `setTimeout(() => this.method(), 10)`

**Comment by Skytrias** [comment]
``function Person(name) {
  // constructor
  this.name = "";

  set_Name = () => {
    this.name = "Michael";
  }
}``

the above actually works fine, omenking fears this might break things

**Comment by Skytrias** [comment]
fixed it, is it still global scope?

**Comment by omenking** [comment]
It would populate global

**Comment by omenking** [comment]
The `autobind` libraries should work but they fail to get around getters and setters and they will go on to bind them which will effectively break their binding. There's no apparent way to detect if a function is a getter or a setter so to skip these cases. There's suppose to be but `getOwnPropertyDescriptor` isn't returning `get` or `set` as documented. So it must not work in our version of chrome

**Comment by Skytrias** [comment]
found a new solution here: https://javascript.info/bind

```javascript
for (let key in this) 
  if (typeof this[key] == 'function')
    user[key] = user[key].bind(this);
```

the above binds all (current) methods to the object. definitely this is better than 20 lines of bindings

**Comment by Skytrias** [comment]
the newest solution doesnt work everywhere. i've been having issues with the autobinding through the above method in the playfield_cursor. i suspect it has to deal with the controls.js. 
it could also be that the constructor doesnt add all of the this bindings quickly enough or out of order so that some methods start calling even tho they dont have a binding yet.

**Comment by Skytrias** [comment]
this problem will either remain unsolved or shouldnt matter once we switch to typescript.
